name: libusb_android_example
description: "Demonstrates how to use the libusb_android plugin."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0

  libusb_android:
    path: ../
  libusb_android_helper: ^1.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true